name: SAA Bot Runner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

concurrency:
  group: xobot-group
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install --no-audit --no-fund
          
      - name: Run Bot
        env:
          U_MAIL: ${{ secrets.U_MAIL }}
          U_PASS: ${{ secrets.U_PASS }}
        run: node index.js
